version: '3'
services:
  framadate:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=framadate
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=your_password
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=framadate
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=your_password
