version: '3'
services:
  framadate:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./framadate-config.php:/var/www/framadate/app/inc/config.php
      - ./htpasswd:/etc/apache2/.htpasswd
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=framadate
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql_data:
