name: Docker-Image CI für GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bild erstellen und veröffentlichen
        run:
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u surmatik --password-stdin
          docker build . --tag ghcr.io/surmatik/framadate-ceviwetzikon:latest
          docker push ghcr.io/surmatik/framadate-ceviwetzikon:latest
