name: Docker-Image CI für GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bild erstellen
        run: docker build . --tag ghcr.io/surmatik/framadate-ceviwetzikon:latest
      - name: Bei GHCR anmelden und veröffentlichen
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u surmatik --password-stdin
          docker push ghcr.io/surmatik/framadate-ceviwetzikon:latest
          
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          
      - name: Execute Webhook
        run: |
          curl -X POST https://portainer.surmatik.ch/api/webhooks/26173694-7824-413c-9ae0-9ccc760de4cc
